# Dependencies needed by build-logic/

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.6" }
errorprone = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version = "4.3.0" }
idea-ext = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version = "1.3" }
jandex = { module = "com.github.vlsi.gradle:jandex-plugin", version = "2.0.0" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
shadow = { module = "com.github.johnrengelman:shadow", version = "8.1.1" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "8.0.0" }
